stages:
  - test-redhat
  - test-arch
  - test-alpine
  - test-ubuntu

#rhel
cacertificates-rhel-tests:
  image: almalinux:latest
  stage: test-redhat
  when: manual
  script:
    - dnf install -y epel-release
    - dnf install -y ansible
    - dnf install -y python39 python3-pip
    - rm -rf venv || true
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    # copy role
    - cp -r $(pwd) /etc/ansible/roles/ca-certificates

    # copy cert to source folder
    - mkdir -p /opt/admin/ca-certificates/
    - cp -r $(pwd)/files/* /opt/admin/ca-certificates/

    - ansible-playbook -vvvvv tests/test.yml
    - pytest --name alma

#arch
cacertificates-archlinux-tests:
  image: archlinux:latest
  stage: test-arch
  when: manual
  script:
    - pacman -Sy
    - pacman --noconfirm -Sy ansible python3 python-pip
    - mkdir -p /etc/ansible/roles
    - rm -rf venv || true
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    # copy role
    - cp -r $(pwd) /etc/ansible/roles/ca-certificates

    # copy cert to source folder
    - mkdir -p /opt/admin/ca-certificates/
    - cp -r $(pwd)/files/* /opt/admin/ca-certificates/

    - ansible-playbook -vvvvv tests/test.yml
    - pytest --name arch

#alpine
cacertificates-alpine-tests:
  image: alpine:latest
  stage: test-alpine
  when: manual
  script:
    - apk update && apk upgrade
    - apk add python3 py-pip ansible
    - mkdir -p /etc/ansible/roles
    - rm -rf venv || true
    - python3 -m venv venv || true
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    # copy role
    - cp -r $(pwd) /etc/ansible/roles/ca-certificates

    # copy cert to source folder
    - mkdir -p /opt/admin/ca-certificates/
    - cp -r $(pwd)/files/* /opt/admin/ca-certificates/

    - ansible-playbook -vvvvv tests/test.yml
    - pytest --name alpine

#ubuntu
cacertificates-ubuntu2004-tests:
  image: ubuntu:20.04
  stage: test-ubuntu
  when: manual
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update --yes
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes tzdata
    - apt-get install --yes software-properties-common
    - add-apt-repository --yes --update ppa:ansible/ansible
    - apt-get install --yes python3 python3-pip python3-venv ansible
    - python3 -m venv venv || true
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    # copy role
    - cp -r $(pwd) /etc/ansible/roles/ca-certificates

    # copy cert to source folder
    - mkdir -p /opt/admin/ca-certificates/
    - cp -r $(pwd)/files/* /opt/admin/ca-certificates/

    - ansible-playbook -vvvvv tests/test.yml
    - pytest --name debian

cacertificates-ubuntu2204-tests:
  image: ubuntu:22.04
  stage: test-ubuntu
  when: manual
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update --yes
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes tzdata
    - apt-get install --yes software-properties-common
    - add-apt-repository --yes --update ppa:ansible/ansible
    - apt-get install --yes python3 python3-pip python3-venv ansible
    - python3 -m venv venv || true
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    # copy role
    - cp -r $(pwd) /etc/ansible/roles/ca-certificates

    # copy cert to source folder
    - mkdir -p /opt/admin/ca-certificates/
    - cp -r $(pwd)/files/* /opt/admin/ca-certificates/

    - ansible-playbook -vvvvv tests/test.yml
    - pytest --name debian

cacertificates-ubuntu2404-tests:
  image: ubuntu:24.04
  stage: test-ubuntu
  #when: manual
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update --yes
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes tzdata
    - apt-get install --yes software-properties-common
    - add-apt-repository --yes --update ppa:ansible/ansible
    - apt-get install --yes python3 python3-pip python3-venv ansible
    - rm -rf venv || true
    - python3 -m venv venv || true
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    # copy role
    - cp -r $(pwd) /etc/ansible/roles/ca-certificates

    # copy cert to source folder
    - mkdir -p /opt/admin/ca-certificates/
    - cp -r $(pwd)/files/* /opt/admin/ca-certificates/

    - ansible-playbook -vvvvv tests/test.yml
    - pytest --name debian


