---
# tasks file for ca-certificates (Alpine specific)

- name: install ca certificates
  apk: name={{ ca_packages }} state=present update_cache=yes
  tags: ca-certificates

- name: Copy ca file to target host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/share/ca-certificates
    owner: root
    group: root
    mode: '0600'
  with_fileglob: "{{ source_glob }}"
  tags: copy-ca-certificates

- name: update certificate store
  ansible.builtin.shell: update-ca-certificates
  tags: ca-certificates